const categories = [
  {
    id: 0,
    name: "All",
  },
  {
    id: 1,
    name: "Trends",
  },
  {
    id: 2,
    name: "Tops",
  },
  {
    id: 3,
    name: "Skirts",
  },
  {
    id: 4,
    name: "GarWon",
  },
  {
    id: 5,
    name: "Pants",
  },
  {
    id: 6,
    name: "Bags",
  },
  {
    id: 7,
    name: "Glasses",
  },
];

const products = [
  {
    id: 1,
    name: "Slim Fit Dress",
    image: "dr1.jpg",
    price: 13000,
    categoryId: 4,
    detail: "loremksfjdiasdf ifewafhusdhfwaidfshvihdfahdfscxbhvzsbcxdvzcxbvhzxbc jbhszhvsfhwgfiuafhwufhsf",
  },
  {
    id: 2,
    name: "One String",
    image: "d4.jpg",
    price: 12000,
    categoryId: 1,
  },
  {
    id: 3,
    name: "Floral Dress",
    image: "dr7.jpg",
    price: 15500,
    categoryId: 1,
  },
  {
    id: 4,
    name: "Bridemaid Dress",
    image: "e1.jpg",
    price: 35000,
    categoryId: 4,
  },
  {
    id: 5,
    name: "Tube Top",
    image: "c14.jpg",
    price: 11000,
    categoryId: 1,
  },
  {
    id: 6,
    name: "Cargo Pant",
    image: "j13.jpg",
    price: 17000,
    categoryId: 5,
  },
  {
    id: 7,
    name: "Crochet skirt",
    image: "s24.jpg",
    price: 22000,
    categoryId: 1,
  },
  {
    id: 8,
    name: "Jean Pant",
    image: "p18.jpg",
    price: 28000,
    categoryId: 5,
  },
  {
    id: 9,
    name: "Jean Flare Pant",
    image: "j4.jpg",
    price: 32000,
    categoryId: 5,
  },
  {
    id: 10,
    name: "Gray long Dress with Slit",
    image: "e4.jpg",
    price: 12000,
    categoryId: 1,
  },
  {
    id: 11,
    name: "Black Mermaid",
    image: "e13.jpg",
    price: 28000,
    categoryId: 4,
  },
  {
    id: 12,
    name: "Black Mermaid",
    image: "e8.jpg",
    price: 27000,
    categoryId: 4,
  },
  {
    id: 13,
    name: "Fancy Glass",
    image: "p27.jpg",
    price: 7000,
    categoryId: 7,
  },
  {
    id: 14,
    name: "Pullover Shirt",
    image: "p23.jpg",
    price: 14000,
    categoryId: 1,
  },
  {
    id: 15,
    name: "Fancy Glass",
    image: "p28.jpg",
    price: 7000,
    categoryId: 7,
  },
  {
    id: 16,
    name: "Fancy Bag",
    image: "b3.jpg",
    price: 7000,
    categoryId: 6,
  },
  {
    id: 17,
    name: "Fancy Bag One",
    image: "b2.jpg",
    price: 8000,
    categoryId: 6,
  },
  {
    id: 18,
    name: "Fancy Bag Two",
    image: "b4.jpg",
    price: 9000,
    categoryId: 6,
  },
];

const limitedProducts = [
  {
    id: 1001,
    name: "Slim Fit Dress",
    image: "dr4.jpg",
    price: 130000,
    categoryId: 1,
    in_stock: true,
  },
  {
    id: 1002,
    name: "One String",
    image: "dr9.jpg",
    price: 120000,
    categoryId: 1,
    in_stock: true,
  },
  {
    id: 1003,
    name: "Floral Dress",
    image: "c23.jpg",
    price: 155000,
    categoryId: 1,
    in_stock: true,
  },
  {
    id: 1004,
    name: "Bridemaid Dress",
    image: "c35.jpg",
    price: 350000,
    categoryId: 1,
    in_stock: true,
  },
  {
    id: 1005,
    name: "Tube Top",
    image: "s9.jpg",
    price: 110000,
    categoryId: 1,
    in_stock: false,
  },
  {
    id: 1006,
    name: "Cargo Pant",
    image: "pro1.jpg",
    price: 170000,
    categoryId: 1,
    in_stock: false,
  },
  {
    id: 1007,
    name: "Crochet skirt",
    image: "b27.jpg",
    price: 220000,
    categoryId: 1,
    in_stock: false,
  },
  {
    id: 1008,
    name: "Crochet skirt",
    image: "s4.jpg",
    price: 210000,
    categoryId: 1,
    in_stock: false,
  },
];
